<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CHECKOUT  (1,138.00)</name>
   <tag></tag>
   <elementGuidId>22322a7a-018e-4ee2-9db7-35e27c5669ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkOutPopUp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='checkOutPopUp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>044a5472-79fe-4512-91df-5af5af9657e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkOutPopUp</value>
      <webElementGuid>b76a7f13-e074-456e-b7cd-f5af84f340a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>check_out_btn</value>
      <webElementGuid>b354bd0c-3cba-4f64-b63d-eb131bf7a9fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>74c8504d-eb76-461a-95f7-6f3bf971f067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-medium ng-binding</value>
      <webElementGuid>dd1d8389-34c9-478c-9d72-a70af71a1f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>checkout($event)</value>
      <webElementGuid>5f18fd22-10fc-4021-8252-c81d69e3a6f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CHECKOUT  ($1,138.00)</value>
      <webElementGuid>6cd22f0f-b074-4a26-b4a1-3edf408e256a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkOutPopUp&quot;)</value>
      <webElementGuid>e80a0452-de16-4ccf-9d2e-84c1daa1c18b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='checkOutPopUp']</value>
      <webElementGuid>74501db2-ceaf-4159-b1b0-c6b65d7e5ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tool-tip-cart[@id='toolTipCart']/div/table/tfoot/tr[2]/td/button</value>
      <webElementGuid>f154cd20-2cdb-4805-bbe6-99c60183bf73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1,138.00'])[1]/following::button[1]</value>
      <webElementGuid>d0a61a62-e8ad-4e48-adaa-19ec0e0e1bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(2 Items)'])[1]/following::button[1]</value>
      <webElementGuid>73ac5154-8c64-4651-ba4c-b8eb98a68dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='namuu'])[2]/preceding::button[1]</value>
      <webElementGuid>2cd1c4e0-4365-4233-8aed-2d170ecae2fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My account'])[2]/preceding::button[1]</value>
      <webElementGuid>eac8bfb7-84f7-419c-8deb-a7add537e2f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/button</value>
      <webElementGuid>f021b7a3-2ea3-4aa0-8ebe-2bac40860da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'checkOutPopUp' and @name = 'check_out_btn' and (text() = 'CHECKOUT  ($1,138.00)' or . = 'CHECKOUT  ($1,138.00)')]</value>
      <webElementGuid>8007ee56-638c-4809-8791-68f73e463a8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
