<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SHOP NOW_23</name>
   <tag></tag>
   <elementGuidId>bdb4642e-5fe6-4864-b737-d00645c43189</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='23']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#23</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9542a5cd-2ef2-435e-b085-b2120628d450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>23</value>
      <webElementGuid>5991cd6b-8cee-41a8-ae86-5250743ae201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imgProduct</value>
      <webElementGuid>b987820e-b649-45af-98d1-5645398ea06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{ outOfStock : product.productStatus == 'OutOfStock' } </value>
      <webElementGuid>6c92c932-f14d-4d8d-9f8d-95d6be6052ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-src</name>
      <type>Main</type>
      <value>/catalog/fetchImage?image_id=4500</value>
      <webElementGuid>107a06a3-c9fd-400e-ba35-f3a785faed89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/catalog/fetchImage?image_id=4500</value>
      <webElementGuid>f78453fe-fb1f-4517-a02d-61f2e2342a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;23&quot;)</value>
      <webElementGuid>f73a7e51-aa01-4315-91c3-765640779a5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='23']</value>
      <webElementGuid>373d8265-f70d-4edb-bef1-5f7aedc9369e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/img</value>
      <webElementGuid>a8c066ba-9b31-49f0-9de7-7c34c7495c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '23' and @src = '/catalog/fetchImage?image_id=4500']</value>
      <webElementGuid>df5ad184-08e4-4beb-91f9-c11d07a29bb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
