<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SHOP NOW_25</name>
   <tag></tag>
   <elementGuidId>9c42c596-19ab-420c-a84d-f6dadb143aee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#25</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='25']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f91d2851-b3b4-48ef-987a-5cc398fd12fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>a5d49496-9872-455a-8cdd-80635a4f9d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imgProduct</value>
      <webElementGuid>986fc28c-f937-483f-b01d-22628037d396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{ outOfStock : product.productStatus == 'OutOfStock' } </value>
      <webElementGuid>9f2a9a32-6351-438d-960b-9bbe76f1afd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-src</name>
      <type>Main</type>
      <value>/catalog/fetchImage?image_id=4700</value>
      <webElementGuid>ba13df2a-5234-4052-abe1-1658f0dc37d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/catalog/fetchImage?image_id=4700</value>
      <webElementGuid>af3efbb3-955b-4066-905e-eb2c8490d970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;25&quot;)</value>
      <webElementGuid>34c93e1f-f978-4aa3-a7a2-cbd930088c21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='25']</value>
      <webElementGuid>aeb26e58-f321-4cfe-98a1-86a5c42cb32c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/img</value>
      <webElementGuid>87a6bbde-c58a-46e3-bb7f-03b0d3209d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '25' and @src = '/catalog/fetchImage?image_id=4700']</value>
      <webElementGuid>f262a1fe-ce37-4838-bb14-da0e68b6153b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
