<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__card_number</name>
   <tag></tag>
   <elementGuidId>d5e1575b-567c-4082-a7a6-b60ad40856d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#creditCard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='creditCard']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f35b988-d31a-44bd-b277-2f02c2ae7a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>creditCard</value>
      <webElementGuid>f3ff2ac1-8cca-43c4-b6a2-c2e3f5c3f684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card_number</value>
      <webElementGuid>53520e79-0848-49ee-b7d2-4ec5db9d6ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>secModel</value>
      <webElementGuid>c6b3c0ef-1324-4a47-bd72-6d8418b26b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>8b26179b-a323-4042-bbc7-e8d4accf546d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-scope ng-valid-maxlength</value>
      <webElementGuid>38aed55a-7c23-4f6e-9c4b-0693b4d74271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;creditCard&quot;)</value>
      <webElementGuid>a7efbe75-e92f-49df-967c-e62d418cdc8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='creditCard']</value>
      <webElementGuid>f19b058f-edf9-48ab-a96b-4470af09fe22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paymentMethod']/div/div[4]/sec-form/div/sec-view/div/input</value>
      <webElementGuid>bf8693f1-25fd-40bf-803e-a73dddfcb436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/sec-form/div/sec-view/div/input</value>
      <webElementGuid>685d0b88-dddd-4da9-a5f4-e56276f51dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'creditCard' and @name = 'card_number']</value>
      <webElementGuid>5a919c7f-0b87-46dd-a9bd-9ecb3e47caf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
