<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Safepay</name>
   <tag></tag>
   <elementGuidId>90025c27-d102-4001-95ea-99aaed4c4e3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Safepay&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='paymentMethod']/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>baf8cccf-96b5-4448-8b78-19556bb36648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>css/images/SafePay.png</value>
      <webElementGuid>9d2f7f36-9e09-4ed4-9611-a3afd1a16404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Safepay</value>
      <webElementGuid>55f4b7cd-d4de-407b-907d-c4e60f101f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentMethod&quot;)/div[1]/div[@class=&quot;paymentMethods&quot;]/div[@class=&quot;imgRadioButton selected&quot;]/img[1]</value>
      <webElementGuid>799867d4-1c95-441a-abf0-09afbed61b57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paymentMethod']/div/div/div/img</value>
      <webElementGuid>96836c28-ac88-41a5-908e-50a5e1587ed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Safepay']</value>
      <webElementGuid>4ee5977d-99ba-4824-a262-6922cc7d3d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/img</value>
      <webElementGuid>ddb9848a-2a37-486d-ac80-8e3dd95c6d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'css/images/SafePay.png' and @alt = 'Safepay']</value>
      <webElementGuid>a4b7ee10-2735-4dac-bcfd-a5903804c4ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
