<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Color_blue</name>
   <tag></tag>
   <elementGuidId>f0930044-773c-4f97-a6aa-e4a95f811752</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//span[@id='bunny'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2f75ec26-bb10-44a0-b445-d383a34e0b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>BLUE</value>
      <webElementGuid>b64e5abb-2e7e-4510-bbf5-a3af995d8f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bunny</value>
      <webElementGuid>bad744c0-db11-4eb5-942b-a0b328c747e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-repeat</name>
      <type>Main</type>
      <value>color in colors</value>
      <webElementGuid>eecfbedc-a188-401b-836f-b4c4fbc74a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bunny productColor ng-scope BLUE</value>
      <webElementGuid>7c0175fc-09b6-49d4-8d2f-7a55f97f6413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-hide</name>
      <type>Main</type>
      <value>color.code == 'ABCDEF'</value>
      <webElementGuid>74517b3a-fbfc-4820-93db-7441c99f57e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-style</name>
      <type>Main</type>
      <value>color.code == 'FFFFFF' ?
                                          {'backgroundColor': '#' + color.code, 'border': 'solid 1px #9d9d9d' } :
                                          {'backgroundColor': '#' + color.code, 'border': 'solid 1px transparent'}</value>
      <webElementGuid>6b08cf7d-d190-4143-989e-719d6e7ad058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{ colorSelected : colorSelected.name == color.name , BLUE : colorSelected.name}</value>
      <webElementGuid>8508206a-5a6b-4fc2-9a25-751571911a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>setColor(color, $event)</value>
      <webElementGuid>9f0bf2d1-5fb0-4adb-ab9c-ba331ad5a843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productProperties&quot;)/div[@class=&quot;colors ng-scope&quot;]/div[2]/span[@id=&quot;bunny&quot;]</value>
      <webElementGuid>8a7e2ad1-9bb3-4fba-a1f8-35877463a54b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@id='bunny'])[3]</value>
      <webElementGuid>423d397c-c44b-4372-a10a-f1aeea4f58d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='productProperties']/div/div[2]/span[3]</value>
      <webElementGuid>7d54fcb7-daa7-4322-b502-d411cbca7e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color:'])[1]/following::span[7]</value>
      <webElementGuid>dda4909c-09f7-4f9f-8b7c-9bc3eb13185b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOLD OUT'])[2]/following::span[7]</value>
      <webElementGuid>366e6b11-e603-48b4-a737-c0f7a74d585c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity:'])[1]/preceding::span[2]</value>
      <webElementGuid>56b8eae2-672c-4468-9359-25e2a6b3b570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Warranty'])[1]/preceding::span[2]</value>
      <webElementGuid>829e6c74-f274-4109-91fd-7c59c2ba448a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span[3]</value>
      <webElementGuid>3a0bd17d-4cc4-4d60-a644-75279c325fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'BLUE' and @id = 'bunny']</value>
      <webElementGuid>13c4c00b-2acc-4b23-af28-4837461cffe0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
