<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Color_tosca</name>
   <tag></tag>
   <elementGuidId>d624707e-64dd-4035-92b3-ebbd34f8cd1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='bunny']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bunny</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8df1a369-1290-47dd-9356-64745b7da588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>TURQUOISE</value>
      <webElementGuid>067d5251-da3a-493d-851c-a316f0436c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bunny</value>
      <webElementGuid>f611cca5-6488-427b-a87f-6016a04ccc4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-repeat</name>
      <type>Main</type>
      <value>color in colors</value>
      <webElementGuid>689b2f0e-6961-4afa-9d70-329e6c8d26dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>productColor ng-scope colorSelected TURQUOISE</value>
      <webElementGuid>9055bc8d-f2c3-4a7f-8fe0-aeb57b31bce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-hide</name>
      <type>Main</type>
      <value>color.code == 'ABCDEF'</value>
      <webElementGuid>f7dec1a2-ed05-427d-89aa-26709fe9f3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-style</name>
      <type>Main</type>
      <value>color.code == 'FFFFFF' ?
                                          {'backgroundColor': '#' + color.code, 'border': 'solid 1px #9d9d9d' } :
                                          {'backgroundColor': '#' + color.code, 'border': 'solid 1px transparent'}</value>
      <webElementGuid>98993ef0-d9aa-4071-bff4-3afdea098c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{ colorSelected : colorSelected.name == color.name , TURQUOISE : colorSelected.name}</value>
      <webElementGuid>3e3aab64-ec2c-4f6b-a503-d5225cea8b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>setColor(color, $event)</value>
      <webElementGuid>4d051a7a-2cca-4657-b754-008b84ae73c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productProperties&quot;)/div[@class=&quot;colors ng-scope&quot;]/div[2]/span[@id=&quot;bunny&quot;]</value>
      <webElementGuid>04a17b0d-2d9d-4624-83e0-37bfb0493b64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='bunny']</value>
      <webElementGuid>60d7660f-ef98-4024-94d6-bd6d053e969e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='productProperties']/div/div[2]/span</value>
      <webElementGuid>7c84c561-9e36-4420-9f11-08331074aeb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color:'])[1]/following::span[5]</value>
      <webElementGuid>564cbcbb-cb95-4ae3-89d1-ff85e792bb2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOLD OUT'])[2]/following::span[5]</value>
      <webElementGuid>dd2a9ad8-6c9a-4ca5-afb4-ee95e91b384c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity:'])[1]/preceding::span[4]</value>
      <webElementGuid>7235ee6b-990c-479f-9102-0bb8fbddbc5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Warranty'])[1]/preceding::span[4]</value>
      <webElementGuid>ba95269b-b5f3-4494-ac9e-644f23c60e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>dbed056f-3822-48c2-8022-edcbab77ef82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'TURQUOISE' and @id = 'bunny']</value>
      <webElementGuid>9be374c9-1cb5-4cb7-90ad-25083bb7eb9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
